### PR TITLE
SSO: validate correct timestamp

### PR DESCRIPTION
**Pull request by danielbeardsley**
* Validate time() against the timestamp in the url
    instead of... you know... time()
 * Validate that all parameters are present.
 * Narrow the valid timestamp window

### CODE REVIEW

**Comment by djmetzle** [comment]
Looks good. CR :+1:

**Comment by entendu** [comment]
`moodle_exception`s are printed to the screen, so it would be more secure to not give precise error messages like `"Missing required URL parameter: $param"`. But that's a minor thing so CR 🥇

**Comment by danielbeardsley** [comment]
To me, which params are required isn't really a security issue because all the params are normally present and visible. You'd have to hand edit a url and remove one to even see the message; at that point, you know which params are being sent. The real security measure is the hash; knowing that it's present doesn't help you brute force it any faster.

**Comment by entendu** [comment]
Error message info leakage is a common vector for determining how to launch and automate attacks. This implementation is open source and available to the public so it's a bit less important (an interested party can simply read the source code) which is why I didn't dev block. Def something to be aware of in our private code though. 

More reading:

https://www.owasp.org/index.php/Top_10_2007-Information_Leakage_and_Improper_Error_Handling

**Comment by danielbeardsley** [comment]
We don't even use Moodle anymore.

**Pull request closed without merging**
